diff --git a/Makefile b/Makefile
index d35f941..8229f7f 100644
--- a/Makefile
+++ b/Makefile
@@ -248,7 +248,6 @@ clean:
 	$(RM) dracut.pc
 	$(RM) dracut-cpio src/dracut-cpio/target/release/dracut-cpio*
 	$(RM) -rf build/ doc_site/modules/ROOT/pages/man/*
-	$(MAKE) -C test clean
 
 syncheck:
 	@ret=0;for i in dracut-initramfs-restore.sh modules.d/*/*.sh; do \
