---
name: Release

on:  # yamllint disable-line rule:truthy
  schedule:
    ## Schedule the job every two months to run on the first of each even month
    - cron: '0 0 1 FEB,APR,JUN,AUG,OCT,DEC *'
  workflow_dispatch:
    inputs:
      tag:
        description: "release version number (3 digits)"
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build
        run: bash ${GITHUB_WORKSPACE}/tools/release.sh ${{ inputs.tag }}
